"""empty message

Revision ID: f8429eddf149
Revises: 481929ef12c7
Create Date: 2024-10-16 23:47:34.362173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8429eddf149'
down_revision: Union[str, None] = '481929ef12c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('valor_referencia', sa.Float(), nullable=False),
    sa.Column('motorizacao', sa.Integer(), nullable=False),
    sa.Column('turbo', sa.Boolean(), nullable=False),
    sa.Column('automatico', sa.Boolean(), nullable=False),
    sa.Column('montadora_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['montadora_id'], ['automaker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_id'), 'vehicle', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicle_id'), table_name='vehicle')
    op.drop_table('vehicle')
    # ### end Alembic commands ###
